{
 "title": "Nethermind",
 "tags": [
  "ethereum",
  "execution-layer",
  "nethermind"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Basic Parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nethermind_sync_peers" }
   ]
  },
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "nethermind_blocks" },
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_json_rpc_bytes_sent[1m])*60",
     "legendFormat": "RPC Sent"
    },
    {
     "expr": "rate(nethermind_json_rpc_bytes_received[1m])*60",
     "legendFormat": "RPC Received"
    },
    {
     "expr": "rate(nethermind_discovery_bytes_received[1m])*60",
     "legendFormat": "Dscv Sent"
    },
    {
     "expr": "rate(nethermind_discovery_bytes_sent[1m])*60",
     "legendFormat": "Dscv Received"
    },
    {
     "expr": "rate(nethermind_p2pbytes_received[1m])*60",
     "legendFormat": "P2P Received"
    },
    {
     "expr": "rate(nethermind_p2pbytes_sent[1m])*60",
     "legendFormat": "P2P Sent"
    }
   ]
  },
  {
   "title": "Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nethermind_version" }
   ]
  },
  {
   "title": "AuRa Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks Sealed (total)",
     "type": "stat",
     "description": "Total number of sealed blocks",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "nethermind_blocks_sealed" }
     ]
    },
    {
     "title": "Failed Block Seals (total)",
     "type": "stat",
     "description": "Total number of failed block seals",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "nethermind_failed_block_seals" }
     ]
    },
    {
     "title": "Aura Step",
     "type": "graph",
     "description": "Current AuRa step",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nethermind_au_ra_step" }
     ]
    },
    {
     "title": "Blocks Production Indicator",
     "type": "stat",
     "description": "Indicator if blocks can be produced",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "nethermind_can_produce_blocks" }
     ]
    },
    {
     "title": "Reported Malicious Misbehaviour",
     "type": "stat",
     "description": "Number of reported malicious misbehaviour validators",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_reported_malicious_misbehaviour"
      }
     ]
    },
    {
     "title": "Sealed Transactions",
     "type": "graph",
     "description": "Number of sealed transactions generated by engine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nethermind_sealed_transactions" }
     ]
    },
    {
     "title": "Reported Benign Misbehaviour",
     "type": "stat",
     "description": "Number of reported benign misbehaviour validators",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_reported_benign_misbehaviour"
      }
     ]
    },
    {
     "title": "Validators Count",
     "type": "stat",
     "description": "Number of current AuRa validators",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "nethermind_validators_count" }
     ]
    },
    {
     "title": "RANDAO Reveal Number",
     "type": "graph",
     "description": "RANDAO number of reveal number transactions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nethermind_reveal_number" }
     ]
    },
    {
     "title": "POSDAO Emit Initiate Change",
     "type": "graph",
     "description": "POSDAO number of emit init change transactions",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_emit_initiate_change"
      }
     ]
    },
    {
     "title": "RANDAO Commit Hash Transaction",
     "type": "graph",
     "description": "RANDAO number of commit hash transactions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_commit_hash_transaction"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "dotnet_total_memory_bytes", "legendFormat": "Managed Memory" },
      {
       "expr": " process_working_set_bytes - dotnet_total_memory_bytes",
       "legendFormat": "Unmanaged Memory"
      }
     ]
    },
    {
     "title": "Memory Growth (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "deriv(dotnet_total_memory_bytes[1m]) > 0",
       "legendFormat": "Managed Memory",
       "target": "*.Nethermind_Runner.*.*.*.*.gauge.*.Process_Physical_Memory"
      }
     ]
    },
    {
     "title": "GC (per minute)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"0\",job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Gen 0"
      },
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"1\",job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Gen 1"
      },
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"2\",job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Gen 2"
      }
     ]
    }
   ]
  },
  {
   "title": "Pruning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Caching Efficiency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_loaded_from_db_nodes_count",
       "legendFormat": "DB"
      },
      {
       "expr": "nethermind_loaded_from_rlp_cache_nodes_count",
       "legendFormat": "RLP Cache"
      },
      {
       "expr": "nethermind_loaded_from_cache_nodes_count",
       "legendFormat": "Node Cache"
      },
      {}
     ]
    },
    {
     "title": "Pruning Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nethermind_memory_used_by_cache"
      }
     ]
    },
    {
     "title": "Pruning Levels",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_committed_nodes_count",
       "legendFormat": "Committed"
      },
      {
       "expr": "nethermind_persisted_node_count",
       "legendFormat": "Persisted"
      },
      { "expr": "nethermind_cached_nodes_count", "legendFormat": "Cached" },
      {
       "expr": "nethermind_replaced_nodes_count",
       "legendFormat": "Replaced"
      },
      {
       "expr": "nethermind_pruned_persisted_nodes_count",
       "legendFormat": "Pruned Persisted"
      },
      {
       "expr": "nethermind_pruned_transient_nodes_count",
       "legendFormat": "Pruned Transient"
      }
     ]
    },
    {
     "title": "Times",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_snapshot_persistence_time",
       "legendFormat": "Persistence"
      },
      { "expr": "nethermind_pruning_time", "legendFormat": "Pruning" },
      { "expr": "nethermind_deep_pruning_time" }
     ]
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block processing time (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_last_block_processing_time_in_ms"
      }
     ]
    },
    {
     "title": "Blocks (per second)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      { "expr": "rate(nethermind_blocks[1m])", "legendFormat": "Blocks" }
     ]
    },
    {
     "title": "Sync Peers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "Sync Peers" }
     ],
     "targets": [
      { "expr": "nethermind_sync_peers", "legendFormat": "Sync Peers" }
     ]
    },
    {
     "title": "State Synced (in bytes)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "nethermind_state_synced", "legendFormat": "State" },
      {
       "expr": "rate(nethermind_state_synced[60m])*3600"
      }
     ]
    },
    {
     "title": "Fast Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nethermind_fast_headers", "legendFormat": "Headers" },
      { "expr": "nethermind_fast_bodies", "legendFormat": "Bodies" },
      { "expr": "nethermind_fast_receipts", "legendFormat": "Receipts" }
     ]
    },
    {
     "title": "Blocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nethermind_blocks" }
     ]
    },
    {
     "title": "CPU time (tracks restarts)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "process_cpu_seconds_total", "legendFormat": "Uptime" }
     ]
    }
   ]
  },
  {
   "title": "JSON RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "JSON RPC (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_json_rpc_successes[1m])*60",
       "legendFormat": "RPC Successes"
      },
      {
       "expr": "rate(nethermind_json_rpc_errors[1m])*60",
       "legendFormat": "RPC Errors"
      },
      {
       "expr": "rate(nethermind_json_rpc_request_deserialization_failures[1m])*60",
       "legendFormat": "Deserialization Failures"
      },
      {
       "expr": "rate(nethermind_json_rpc_invalid_requests[1m])*60",
       "legendFormat": "Invalid Requests"
      }
     ]
    },
    {
     "title": "JSON RPC (total)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      { "expr": "nethermind_json_rpc_requests", "legendFormat": "RPC Requests" },
      { "expr": "nethermind_json_rpc_successes", "legendFormat": "RPC Successes" },
      { "expr": "nethermind_json_rpc_errors", "legendFormat": "RPC Errors" },
      {
       "expr": "nethermind_json_rpc_request_deserialization_failures",
       "legendFormat": "Deserialization Failures"
      },
      {
       "expr": "nethermind_json_rpc_invalid_requests",
       "legendFormat": "Invalid Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Beam",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Beamed Transactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nethermind_beamed_transactions", "legendFormat": "Transactions" }
     ]
    },
    {
     "title": "Beamed Blocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nethermind_beamed_blocks", "legendFormat": "Blocks" }
     ]
    },
    {
     "title": "Beamed Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nethermind_beamed_requests", "legendFormat": "Requests" }
     ]
    },
    {
     "title": "Beamed Trie Nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nethermind_beamed_trie_nodes", "legendFormat": "Trie Nodes" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections (per minute)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_incoming_connections[1m])*60",
       "legendFormat": "Incoming Connections"
      },
      {
       "expr": "rate(nethermind_outgoing_connections[1m])*60",
       "legendFormat": "Outgoing Connections"
      },
      {
       "expr": "rate(nethermind_handshakes[1m])*60",
       "legendFormat": "Handshakes"
      },
      {
       "expr": "rate(nethermind_hellos_sent[1m])*60",
       "legendFormat": "Hellos Sent"
      },
      {
       "expr": "rate(nethermind_hellos_received[1m])*60",
       "legendFormat": "Hellos Received"
      },
      {
       "expr": "rate(nethermind_statuses_sent[1m])*60",
       "legendFormat": "Statuses Sent"
      },
      {
       "expr": "rate(nethermind_statuses_received[1m])*60",
       "legendFormat": "Statuses Received"
      }
     ]
    },
    {
     "title": "Pending Txs (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_pending_transactions_received[1m])*60",
       "legendFormat": "Received"
      },
      {
       "expr": "rate(nethermind_pending_transactions_known[1m])*60",
       "legendFormat": "Already Known"
      },
      {
       "expr": "rate(nethermind_pending_transactions_discarded[1m])*60",
       "legendFormat": "Discarded"
      },
      {
       "expr": "rate(nethermind_pending_transactions_too_far_in_future[1m])*60",
       "legendFormat": "Too far in future"
      },
      {
       "expr": "rate(nethermind_pending_transactions_too_low_fee[1m])*60",
       "legendFormat": "Too low fee"
      },
      {
       "expr": "rate(nethermind_pending_transactions_added[1m])*60",
       "legendFormat": "Added (all)"
      },
      {
       "expr": "rate(nethermind_pending1559transactions_added[1m])*60",
       "legendFormat": "Added (1559)"
      },
      {
       "expr": "rate(nethermind_pending_transactions_evicted[1m])*60",
       "legendFormat": "Evicted"
      },
      {
       "expr": "rate(nethermind_pending_transactions_sent[1m])*60",
       "legendFormat": "Sent txs"
      },
      {
       "expr": "rate(nethermind_pending_transactions_hashes_sent[1m])*60",
       "legendFormat": "Sent hashes"
      }
     ]
    },
    {
     "title": "Disconnects (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_too_many_peers_disconnects[1m])*60",
       "legendFormat": "Too Many Peers"
      },
      {
       "expr": "rate(nethermind_client_quitting_disconnects[1m])*60",
       "legendFormat": "Client Quitting"
      },
      {
       "expr": "rate(nethermind_receive_message_timeout_disconnects[1m])*60",
       "legendFormat": "Receive Timeouts"
      },
      {
       "expr": "rate(nethermind_already_connected_disconnects[1m])*60",
       "legendFormat": "Already Connected"
      },
      {
       "expr": "rate(nethermind_breach_of_protocol_disconnects[1m])*60",
       "legendFormat": "Breach of Protocol"
      },
      {
       "expr": "rate(nethermind_incompatible_p2pdisconnects[1m])*60",
       "legendFormat": "Incompatible P2P"
      },
      {
       "expr": "rate(nethermind_null_node_identity_disconnects{job=\"nethermind\",_instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Null Identity"
      },
      {
       "expr": "rate(nethermind_unexpected_identity_disconnects[1m])*60",
       "legendFormat": "Unexpected Identity"
      },
      {
       "expr": "rate(nethermind_useless_peer_disconnects[1m])*60",
       "legendFormat": "Useless Peer"
      },
      {
       "expr": "rate(nethermind_diconnect_requested_disconnects[1m])*60",
       "legendFormat": "Requested"
      },
      {
       "expr": "rate(nethermind_tcp_subsystem_error_disconnects[1m])*60",
       "legendFormat": "TCP Error"
      },
      {
       "expr": "rate(nethermind_same_as_self_disconnects[1m])*60",
       "legendFormat": "Same as Self"
      },
      {
       "expr": "rate(nethermind_other_disconnects[1m])*60",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Eth62, Eth63, Eth65, Eth66 (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_eth62get_block_headers_received[1m])*60",
       "legendFormat": "GetBlockHeaders eth62"
      },
      {
       "expr": "rate(nethermind_eth62block_headers_received[1m])*60",
       "legendFormat": "BlockHeaders eth62"
      },
      {
       "expr": "rate(nethermind_eth62get_block_bodies_received[1m])*60",
       "legendFormat": "GetBlockBodies eth62"
      },
      {
       "expr": "rate(nethermind_eth62block_bodies_received[1m])*60",
       "legendFormat": "BlockBodies eth62"
      },
      {
       "expr": "rate(nethermind_eth62transactions_received[1m])*60",
       "legendFormat": "Txs received eth62"
      },
      {
       "expr": "rate(nethermind_eth65get_pooled_transactions_received[1m])*60",
       "legendFormat": "Txs requests received eth65"
      },
      {
       "expr": "rate(nethermind_eth65get_pooled_transactions_requested[1m])*60",
       "legendFormat": "Txs requested eth65"
      },
      {
       "expr": "rate(nethermind_eth65pooled_transactions_received[1m])*60",
       "legendFormat": "Txs received eth65"
      },
      {
       "expr": "rate(nethermind_eth62new_block_hashes_received[1m])*60",
       "legendFormat": "NewBlockHashes eth62"
      },
      {
       "expr": "rate(nethermind_eth62new_block_received[1m])*60",
       "legendFormat": "NewBlock eth62"
      },
      {
       "expr": "rate(nethermind_eth63get_node_data_received[1m])*60",
       "legendFormat": "GetNodeData eth63"
      },
      {
       "expr": "rate(nethermind_eth63node_data_received[1m])*60",
       "legendFormat": "NodeData eth63"
      },
      {
       "expr": "rate(nethermind_eth63get_receipts_received[1m])*60",
       "legendFormat": "GetReceipts eth63"
      },
      {
       "expr": "rate(nethermind_eth63receipts_received[1m])*60",
       "legendFormat": "Receipts eth63"
      },
      {
       "expr": "rate(nethermind_eth66get_block_headers_received[1m])*60",
       "legendFormat": "GetBlockHeaders eth66"
      },
      {
       "expr": "rate(nethermind_eth66block_headers_received[1m])*60",
       "legendFormat": "BlockHeaders eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_block_bodies_received[1m])*60",
       "legendFormat": "GetBlockBodies eth66"
      },
      {
       "expr": "rate(nethermind_eth66block_bodies_received[1m])*60",
       "legendFormat": "BlockBodies eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_pooled_transactions_received[1m])*60",
       "legendFormat": "Txs requests received eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_pooled_transactions_requested[1m])*60",
       "legendFormat": "Txs requested eth66"
      },
      {
       "expr": "rate(nethermind_eth66pooled_transactions_received[1m])*60",
       "legendFormat": "Txs received eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_node_data_received[1m])*60",
       "legendFormat": "GetNodeData eth66"
      },
      {
       "expr": "rate(nethermind_eth66node_data_received[1m])*60",
       "legendFormat": "NodeData eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_receipts_received[1m])*60",
       "legendFormat": "GetReceipts eth66"
      },
      {
       "expr": "rate(nethermind_eth66receipts_received[1m])*60",
       "legendFormat": "Receipts eth66"
      }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receipts DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_receipts_db_reads[10s])",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_receipts_db_writes[10s])",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Code DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_code_db_reads[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_code_db_writes[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "State Tree",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_state_tree_reads[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_state_tree_writes[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Block Info DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_block_infos_db_reads[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_block_infos_db_writes[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "State DB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_state_db_reads[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_state_db_writes[1m])*60",
       "legendFormat": "Writes"
      },
      {
       "expr": "rate(nethermind_state_db_in_pruning_writes[1m])*60",
       "legendFormat": "Pruning Writes"
      }
     ]
    },
    {
     "title": "Storage Tree",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_storage_tree_reads[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_storage_tree_writes[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Trie Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_tree_node_rlp_decodings[1m])*60",
       "legendFormat": "RLP.Encode"
      },
      {
       "expr": "rate(nethermind_tree_node_rlp_encodings[1m])*60",
       "legendFormat": "RLP.Decode"
      },
      {
       "expr": "rate(nethermind_tree_node_hash_calculations[1m])*60",
       "legendFormat": "Keccak"
      }
     ]
    },
    {
     "title": "Other DB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_other_db_reads[10s])",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_other_db_writes[10s])",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Blocks DB (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_blocks_db_reads[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_blocks_db_writes[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    }
   ]
  },
  { "title": "TxPool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "DarkPool",
   "type": "graph",
   "description": "Unknown transactions in blocks",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nethermind_dark_pool_ratio_level1",
     "legendFormat": "Level1 (not known)"
    },
    {
     "expr": "nethermind_dark_pool_ratio_level2",
     "legendFormat": "level2 (not pending)"
    }
   ]
  },
  {
   "title": "1559-type transactions ratio",
   "type": "timeseries",
   "description": "Ratio of 1559-type transactions in the block.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nethermind_eip1559transactions_ratio"
    }
   ]
  }
 ]
}