name: "Release"
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "v[0-9]+.[0-9]+.[0-9]+"

    paths-ignore:
      - "README.md"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: npx @dappnode/dappnodesdk publish patch --dappnode_team_preset --timeout 2h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVELOPER_ADDRESS: "0xf35960302a07022aba880dffaec2fdd64d5bf1c1"
