name: "Main"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"
      - "main"
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "README.md"

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v3
      - run: npx @dappnode/dappnodesdk build --skip_save
  
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: npx @dappnode/dappnodesdk publish patch --dappnode_team_preset --timeout 2h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVELOPER_ADDRESS: "0xf35960302a07022aba880dffaec2fdd64d5bf1c1"
