name: "Test Build"
on:
  pull_request:
    branches:
      - "master"
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
