name: "Test"
on:
  pull_request:
    branches:
      - "master"
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    steps:
      - uses: actions/checkout@v3
      - run: npx @dappnode/dappnodesdk build --skip_save

  e2e-test:
    runs-on: mainnet
    needs: build-test
    name: End to end tests
    steps:
      - uses: actions/checkout@v3
      - run: npx @dappnode/dappnodesdk@latest github-action test-end-to-end --errorLogsTimeout 120 --healthCheckUrl http://nethermind.public.dappnode:8545 --network mainnet
